trial merge
IHTSDO/snowstorm-x pull request #13
Opened 2024-12-11 09:25 UTC by bdc-ehealth

2024-12-11 14:16 UTC, kaicode commented
@bdc-ehealth would you like me to review these changes?

There are some files changed that you may not have intended so I wanted to confirm first:
- src/main/resources/application.properties
- zipke.tgz
- zipke.zip
- src/main/resources/git.properties (I'm not familiar with this plugin but the config file seems to contain your details)

2024-12-11 15:11 UTC, bdc-ehealth commented
Hi Kai, this is my first merge to your project, so bear with me. I have been practicing the dark art of solving merge conflicts, in order to be able to get this far...

You are right, there are some superfluous files (zipke.zip and zipke.tgz). The modifications to application.properties are intended. 
git.properties should probably be excluded, as it is generated each time you build the project, but it is needed at runtime. But maybe we should discuss the reasons for its use via PMs on zulip before you proceed with the merge.

2025-01-02 19:51 UTC, bdc-ehealth commented
@kaicode ,

this seems to be about ready. These changes should cater for the metadata group and the simple-cases group.

2025-01-14 14:16 UTC, kaicode commented
Thanks for the update @bdc-ehealth, I'll try to review this in the next week.

2025-01-23 17:54 UTC, kaicode requested changes
This is looking really good @bdc-ehealth, this work clearly represents significant effort, thank you so much.
I've made some comments of things that should be addressed before this PR is accepted. Give me a shout if you would like me to pitch in and fix some of them, I don't want us to fall over each other.

2025-01-23 17:54 UTC, kaicode commented on src/main/java/org/snomed/snowstorm/fhir/services/FHIRConceptService.java
> +		if (Objects.isNull(codeSystemVersion.getHierarchyMeaning()) || "is-a".equals(codeSystemVersion.getHierarchyMeaning())) {
Is it correct behaviour to enable subsumption testing when the codesystem has no hierarchy meaning?
The R4 CodeSystem documentation says
```
Concept A is considered to be subsumed by Concept B if it comes under Concept B in the hierarchy, or if a parent/child relationship is declared in the properties, and the hierarchyMeaning is "is-a"
```

This behaviour is not consistent with the documentation.

2025-01-23 17:54 UTC, kaicode commented on src/main/java/org/snomed/snowstorm/fhir/services/FHIRConceptService.java
> +		logger.info("QUERY:"+searchQuery.getQuery().toString());
Maybe this could be DEBUG now.

2025-01-23 17:54 UTC, kaicode commented on src/main/java/org/snomed/snowstorm/fhir/services/FHIRLoadPackageService.java
> +		byte[] packageBytes = FileUtils.readFileToByteArray(packageFile);
Reading the uploaded package into memory would cause the server to crash if a very large file is uploaded.
Can't we use a FileInputStream here instead of ByteArrayInputStream?

2025-01-23 17:54 UTC, kaicode commented on src/main/java/org/snomed/snowstorm/fhir/services/FHIRLoadPackageService.java
> +				CodeSystem codeSystem = extractObject(new ByteArrayInputStream(packageBytes), filename, CodeSystem.class, jsonParser);
Replace with FileInputStream?

2025-01-23 17:54 UTC, kaicode commented on src/main/java/org/snomed/snowstorm/fhir/services/FHIRLoadPackageService.java
> +				ValueSet valueSet = extractObject(new ByteArrayInputStream(packageBytes), filename, ValueSet.class, jsonParser);
Replace with FileInputStream?

2025-01-23 17:54 UTC, kaicode commented on src/main/java/org/snomed/snowstorm/fhir/services/FHIRValueSetProvider.java
> +				logger.info(FHIRValueSetProviderHelper.getFullURL(request));
Fix indentation

2025-01-23 17:54 UTC, kaicode commented on src/main/java/org/snomed/snowstorm/fhir/services/FHIRValueSetProvider.java
> +				throw new RuntimeException(e);
Please replace with RuntimeServiceException

2025-01-23 17:54 UTC, kaicode commented on src/main/java/org/snomed/snowstorm/fhir/services/FHIRValueSetProviderHelper.java
> +			throw new RuntimeException(e);
Replace with FHIRHelper.exception("Invalid url parameter.", IssueType.INVALID, 400)
Could tighten the scope of this try block too.

2025-01-23 17:54 UTC, kaicode commented on src/main/java/org/snomed/snowstorm/fhir/services/FHIRValueSetProviderHelper.java
> +			throw new RuntimeException(e);
Replace this Exception for URL parsing, see previous comment.

2025-01-23 17:54 UTC, kaicode commented on src/main/java/org/snomed/snowstorm/fhir/services/FHIRValueSetProviderHelper.java
> +		ByteArrayOutputStream baos = new ByteArrayOutputStream();
How big do we expect these files to be?
Can we use a temp file here instead of loading everything into memory?

2025-01-23 17:54 UTC, kaicode commented on src/main/java/org/snomed/snowstorm/fhir/services/FHIRValueSetService.java
> +		//notSupported("excludeNested", params.getExcludeNested());
Looks like this is supported now. Let's remove the line.

2025-01-23 17:54 UTC, kaicode commented on src/main/java/org/snomed/snowstorm/fhir/services/FHIRValueSetService.java
> +        //this line was removed because of the GG tests.
Let's talk about this, I would like to understand.
Currently Snowstorm supports ValueSet/$expand?url=xxx&displayLanguage=es,en-gb
This selects the PT to display for SNOMED CT concepts.

2025-01-23 17:54 UTC, kaicode commented on src/main/java/org/snomed/snowstorm/fhir/services/FHIRValueSetService.java
> +					//.setType(conceptConstraint.getType())
Remove?

2025-01-23 17:54 UTC, kaicode commented on src/main/java/org/snomed/snowstorm/fhir/services/FHIRValueSetService.java
> +								"Supported filters for generic code systems are: (concept, is-a), (concept, descendant-of), (<any>, =).", OperationOutcome.IssueType.NOTSUPPORTED, 400);
Nice

2025-01-23 17:54 UTC, kaicode commented on src/main/java/org/snomed/snowstorm/fhir/services/FHIRValueSetService.java
> +			if (FHIRHelper.isSnomedUri(codeSystemVersion.getUrl()) || codeSystemVersion.getUrl().equals("http://loinc.org") || codeSystemVersion.getUrl().startsWith("http://hl7.org/fhir/sid/icd-10")) {
Please use FHIRConstants for these URI strings. ICD-10 is already there, loinc should be added.

2025-01-23 17:54 UTC, kaicode commented on src/main/java/org/snomed/snowstorm/fhir/services/HapiParametersMapper.java
> +		//Parameters.ParametersParameterComponent param = parameters.addParameter().setName(PROPERTY);
Remove dead code.

2025-01-24 08:52 UTC, bdc-ehealth commented on src/main/java/org/snomed/snowstorm/fhir/services/FHIRConceptService.java
> +		if (Objects.isNull(codeSystemVersion.getHierarchyMeaning()) || "is-a".equals(codeSystemVersion.getHierarchyMeaning())) {
@kaicode Maybe there is a problem in the test, because I could not make the test work without adding this. I'll remove it and check again. If the problem persists, we will have to call out to Grahame Grieve.

2025-01-24 08:53 UTC, bdc-ehealth commented on src/main/java/org/snomed/snowstorm/fhir/services/FHIRConceptService.java
> +		logger.info("QUERY:"+searchQuery.getQuery().toString());
Sure...

2025-01-24 08:56 UTC, bdc-ehealth commented on src/main/java/org/snomed/snowstorm/fhir/services/FHIRLoadPackageService.java
> +		byte[] packageBytes = FileUtils.readFileToByteArray(packageFile);
@kaicode That would mean that you presuppose to have write access somewhere on the filesystem where snowstorm is running. Does snowstorm already have such a place? Is there something I can reuse?

2025-01-24 08:56 UTC, bdc-ehealth commented on src/main/java/org/snomed/snowstorm/fhir/services/FHIRLoadPackageService.java
> +				CodeSystem codeSystem = extractObject(new ByteArrayInputStream(packageBytes), filename, CodeSystem.class, jsonParser);
see: https://github.com/IHTSDO/snowstorm-x/pull/13#discussion_r1928347449

2025-01-24 08:57 UTC, bdc-ehealth commented on src/main/java/org/snomed/snowstorm/fhir/services/FHIRLoadPackageService.java
> +				ValueSet valueSet = extractObject(new ByteArrayInputStream(packageBytes), filename, ValueSet.class, jsonParser);
see: https://github.com/IHTSDO/snowstorm-x/pull/13#discussion_r1928347449

2025-01-24 09:03 UTC, bdc-ehealth commented on src/main/java/org/snomed/snowstorm/fhir/services/FHIRValueSetService.java
> +        //this line was removed because of the GG tests.
@kaicode The line as it is there is too indiscriminate for the tests. In the mods for the "language" package, I add additional code to implement the requirements here: https://build.fhir.org/ig/HL7/fhir-tx-ecosystem-ig/languages.html#client-language-specification , which are for the client, but also permeate in how the server is supposed to respond.

2025-01-24 09:06 UTC, bdc-ehealth commented on src/main/java/org/snomed/snowstorm/fhir/services/FHIRValueSetService.java
> +								"Supported filters for generic code systems are: (concept, is-a), (concept, descendant-of), (<any>, =).", OperationOutcome.IssueType.NOTSUPPORTED, 400);
Thanks...

2025-01-24 09:06 UTC, bdc-ehealth commented on src/main/java/org/snomed/snowstorm/fhir/services/FHIRValueSetService.java
> +			if (FHIRHelper.isSnomedUri(codeSystemVersion.getUrl()) || codeSystemVersion.getUrl().equals("http://loinc.org") || codeSystemVersion.getUrl().startsWith("http://hl7.org/fhir/sid/icd-10")) {
No prob.

2025-01-24 09:06 UTC, bdc-ehealth commented on src/main/java/org/snomed/snowstorm/fhir/services/HapiParametersMapper.java
> +		//Parameters.ParametersParameterComponent param = parameters.addParameter().setName(PROPERTY);
OK

2025-01-24 09:22 UTC, bdc-ehealth commented on src/main/java/org/snomed/snowstorm/fhir/services/FHIRConceptService.java
> +		if (Objects.isNull(codeSystemVersion.getHierarchyMeaning()) || "is-a".equals(codeSystemVersion.getHierarchyMeaning())) {
@kaicode This is the result if I remove the additional condition:
```
Run terminology service Tests
  Source for tests: hl7.fhir.uv.tx-ecosystem#dev
  Output Directory: C:\temp\empty\fhir-tx-ecosystem-ig/snowstormx
  Term Service Url: http://localhost:8080/fhir
  External Strings: false
  Test  Exec Modes: [flat]
Connect to http://localhost:8080/fhir
Load Tests from hl7.fhir.uv.tx-ecosystem#dev
Group metadata
  Test metadata: Pass (00:00:00.34)
  Test term-caps: Pass (00:00:00.3)
Group simple-cases
  Test simple-expand-all: Pass (00:00:01.49)
  Test simple-expand-active: Pass (00:00:00.683)
  Test simple-expand-inactive: Pass (00:00:00.671)
  Test simple-expand-enum: Pass (00:00:00.692)
  Test simple-expand-enum-bad: Pass (00:00:01.456)
  Test simple-expand-isa: Fail (00:00:00.679)
    number property values differ at .expansion.total
Expected:"5" for simple-expand-isa
Actual  :"1"
  Test simple-expand-prop: Pass (00:00:00.653)
  Test simple-expand-regex: Pass (00:00:00.637)
  Test simple-expand-regex2: Pass (00:00:00.634)
  Test simple-lookup-1: Pass (00:00:00.34)
  Test simple-lookup-2: Pass (00:00:00.28)
SnowstormX FHIR Server v10.6.0-SNAPSHOT failed 1 of 13 HL7 terminology service tests (mode flat, tests v1.7.0, runner v6.5.6)
Failed Tests: simple-cases/simple-expand-isa
```
Either the test is wrong, or the doc is wrong...

2025-01-24 10:15 UTC, bdc-ehealth commented on src/main/java/org/snomed/snowstorm/fhir/services/FHIRLoadPackageService.java
> +		byte[] packageBytes = FileUtils.readFileToByteArray(packageFile);
@kaicode I replaced it with a FileInputStream to a temp file. Let's pray we have access to the temp directory on the filesystem.

2025-01-24 10:20 UTC, bdc-ehealth commented on src/main/java/org/snomed/snowstorm/fhir/services/FHIRValueSetService.java
> +					//.setType(conceptConstraint.getType())
OK

2025-01-24 10:51 UTC, bdc-ehealth commented on src/main/java/org/snomed/snowstorm/fhir/services/FHIRValueSetProvider.java
> +				logger.info(FHIRValueSetProviderHelper.getFullURL(request));
OK

2025-01-24 10:52 UTC, bdc-ehealth commented on src/main/java/org/snomed/snowstorm/fhir/services/FHIRValueSetProvider.java
> +				throw new RuntimeException(e);
OK

2025-01-24 10:53 UTC, bdc-ehealth commented on src/main/java/org/snomed/snowstorm/fhir/services/FHIRValueSetProviderHelper.java
> +			throw new RuntimeException(e);
OK

2025-01-24 12:29 UTC, bdc-ehealth commented on src/main/java/org/snomed/snowstorm/fhir/services/FHIRValueSetProviderHelper.java
> +		ByteArrayOutputStream baos = new ByteArrayOutputStream();
@ they are rather small, around 1.4 KB... But if you like a file better, here we go...

2025-01-24 13:56 UTC, bdc-ehealth commented on src/main/java/org/snomed/snowstorm/fhir/services/FHIRValueSetProviderHelper.java
> +			throw new RuntimeException(e);
OK

2025-01-24 13:58 UTC, bdc-ehealth commented on src/main/java/org/snomed/snowstorm/fhir/services/FHIRValueSetService.java
> +		//notSupported("excludeNested", params.getExcludeNested());
OK

2025-01-24 17:14 UTC, kaicode approved these changes
Great, let's merge.
We can sort out the language parameter behaviour later.

2025-01-24 17:14 UTC, merged